### ISSUE TITLE
Spell effects duration

### ISSUE THREAD

**Issue by gatperdut** [tapahob/BG2RadarOverlay#10]
Cheesus, those are `<turn>.<round>`, right? 😍

Here's some stuff I found:

Just as a reminder, 1 in-game hour is 6 minutes real-life, which is 6 turns, which is 60 rounds.

* Spells that have the duration in in-game hours seem to be off (kinda silly of me because they are so long-lasting, but I wanted to point it out in case there's some bug somewhere. Or maybe my math is wrong?):
   *  Armor: 9 in-game hours, or 54 minutes real-life, or 54 turns, or 540 rounds. The card shows `45.0` instead of `54.0`.
   * Stoneskin: 12 in-game hours, or 72 minutes real-life, or 72 turns, or 720 rounds. The card shows `60.0` instead of `72.0`.
   * Protection from normal missiles: 1 in-game hour, or 6 minutes real-life, or 6 turns, or 60 rounds. The card shows `5.0` instead of `6.0`.

Spells with duration in turns or rounds look ok! Tested with Mirror Image and a few others.

* Making the duration numbers bigger would make them more legible, I feel they are too small. For my eyes, anyway (:

* I see you added a default icon for spell icons you don't have in the codebase. It's hard to tell which spells they are without going over them one by one with the mouse. Maybe show them in a dedicated, separate card, with the name included next to the icon, and activated in some other way than right-click?

Otherwise super cool.

**Comment by tapahob** [comment]
It is turn.round yes. 

I checked some of the spells - they seem to disappear correctly right in time when it disappears in game. Will have a look at it.

As for spell icons - Im not given up yet on the ingame texture format. If I win this it would load any icon from the game resources themselves.

**Comment by gatperdut** [comment]
Been testing for a bit, the icons for most of the effects I have seen do show up 😍 If I find more I'll post them in a bundle

**Comment by tapahob** [comment]
I saw Chain Contingency Icon wasn't found. Maybe it would be the same with all the white icons?

**Comment by tapahob** [comment]
Quickly checked it. All the white icons are displayed properly (in the new latest release).
Lich's Chain Contingency is actually a separate spell (pretty sure it is a modified SCS version)

As for durations - I calculate those as gameticks (1/15th of a game second) / 15 (seconds) / 6 (rounds) / 10 (turns)

**Comment by gatperdut** [comment]
Awesome, I did some quick testing and everything looked as it should. Unsure why it was showing the way it did. Clooosing.
