### ISSUE TITLE
Examine party members?

### ISSUE THREAD

**Issue by gatperdut** [tapahob/BG2RadarOverlay#13]
It'd be nice to examine your own party members, and the main character.

Admittedly most of the info is available on the character sheet, but an important bit of missing info is the spell effects durations ("How long until that PFMW wears off?") which Radar, on the other hand, provides.

**Comment by tapahob** [comment]
It should be working if without SCS, gotta investigate how SCS brakes it

**Comment by tapahob** [comment]
Should be fixed in the latest release
