### ISSUE TITLE
Windows Defender False Positive

### ISSUE THREAD

**Issue by Ameranth** [tapahob/BG2RadarOverlay#17]
Hello and thank you for this wonderful project!

Windows Defender is detecting a virus in the download since V2.0.3.2; versions before this were fine.

**Comment by tapahob** [comment]
Hii Ameranth! 
Thank you for checking it out!

Not sure what causes those false positives, the changes in 2.0.3.2 were quite minor.
I guess, for those concerned about it, I can only suggest building the binary for themselves

**Comment by Ameranth** [comment]
Yeah lol to be honest I was surprised it didn't get flagged earlier.

But I figured I'd let you know; I'll close this since you've seen it and there's not much to do about it
