### ISSUE TITLE
Bottom part of list visible with many enemies

### ISSUE THREAD

**Issue by gatperdut** [tapahob/BG2RadarOverlay#18]
When there are lots of enemies on screen, the last entries in the list can still be seen. Kobolds, who come in hordes, are particularly adept at this.

Some solutions I can think of:

* Slide the list further up.
* Make the list invisible after the sliding animation finishes, then visible again when the user wants to display it.
* Slide left?

In general I think a more aproppriate place for the ui elements would be the botton left of the screen instead of the top left, with the list sliding down to hide and and up to show.

**Comment by tapahob** [comment]
Oh thats weird, could you provide a save such an encounter?
Or maybe I can figure it out from the code

**Comment by tapahob** [comment]
I've updated the latest release, please see if it helped

**Comment by gatperdut** [comment]
definitely looks fixed!
