### ISSUE TITLE
Magic Damage Resistance overflows

### ISSUE THREAD

**Issue by gatperdut** [tapahob/BG2RadarOverlay#2]
I noticed that for double/triple digit values the Magic Damage Resistance overflows out of the card and is hidden. Screenshot from the Crooked Crane Lich:

![resist_magic_damage_oob](https://user-images.githubusercontent.com/1401888/170999552-2591a42e-5b19-4eb6-8a0d-6013818aae95.png)

Maybe it could be renamed to Resist Magic Dmg? So as not to mess with the rest of the card layout.

**Comment by tapahob** [comment]
Fixed in the [latest release](https://github.com/tapahob/BG2RadarOverlay/releases/download/1.2.1/BGOverlayUI.7z)
