### ISSUE TITLE
Right-click in inventory opens card

### ISSUE THREAD

**Issue by gatperdut** [tapahob/BG2RadarOverlay#21]
To reproduce:
1) place the mouse over a character.
2) open the inventory with the hotkey
3) right-clicking (to examine an item's description, e.g.) opens the card for the previous character, regardless of where the mouse is currently located

PS. <3 alphabetical order

**Comment by tapahob** [comment]
Thanks for submitting it!

This one would be tricky to figure out

**Comment by tapahob** [comment]
Some more info on the topic

If we are going to filter out the input from other screens we are to find the CScreen struct from CChitin -> pActiveEngine
Thanks @Eeks for the advice:
```
If you haven't found this yet, that would be https://eeex-docs.readthedocs.io/en/latest/EE%20Game%20Structures%20%28x64%29/CC/index.html#cchitin -> pActiveEngine
which is one of the CScreen* structs: https://eeex-docs.readthedocs.io/en/latest/EE%20Game%20Structures%20%28x64%29/CS/index.html
```

The problem is that I currently don't have a static pointer to CChitin. Once its found it would be an easy fix
