### ISSUE TITLE
Right clicking breaks after the game process restart

### ISSUE THREAD

**Issue by tapahob** [tapahob/BG2RadarOverlay#26]

**Comment by Nesae-avi** [comment]
I cannot reproduce the issue. Does it occur when clicking on a particular entity / window?

**Comment by tapahob** [comment]
> I cannot reproduce the issue. Does it occur when clicking on a particular entity / window?

It happen when I tried to right-click my own party members, like it worked before game restart, but after the restart (without restarting the overlay it stopped working)

**Comment by Nesae-avi** [comment]
The mouse hook was not reinitialized for the new process instance which caused the issue.
