### ISSUE TITLE
Duplicate protections

### ISSUE THREAD

**Issue by gatperdut** [tapahob/BG2RadarOverlay#3]
Some of the Status Effect Immunities seem duplicated. Screenshot from the Jailkeep Golem in Irenicus' dungeon:

![golem_duplicated_protections](https://user-images.githubusercontent.com/1401888/170999942-02baeff0-5f2a-4c06-80de-c46a9a7202ff.png)

The lower set of immunities looks more complete, so probably only those should be kept?

Also, question, what does the `1` mean next to `Backstab Immunity`?

**Comment by tapahob** [comment]
Done
