### ISSUE TITLE
Licensing a repository

### ISSUE THREAD

**Issue by Nesae-avi** [tapahob/BG2RadarOverlay#31]
I suggest adding license information to encourage open source contributions.

https://choosealicense.com
https://choosealicense.com/no-license

**Comment by tapahob** [comment]
Which license should I go with?

I welcome anyone to do whatever they wish with the code

**Comment by Nesae-avi** [comment]
> I welcome anyone to do whatever they wish with the code

In this case a short and permissive MIT license seems to be a good choice.
This guide outlines how to use license templates: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by tapahob** [comment]
Done.
