### ISSUE TITLE
Newer versions reading positive on Virus Total

### ISSUE THREAD

**Issue by KyleBrown-804** [tapahob/BG2RadarOverlay#36]
I grabbed version 2.0.6.4 and a couple minor version releases prior and extracted the .exe and uploaded to Virus Total, Ikarus is flagging it as a Trojan, grabbing a version much further back like 2.0.4.3 from the screenshot the .exe doesn't flag anything but newer versions (not sure how far back) do.

Report: https://www.virustotal.com/gui/file/2fa9ea5a581b0d2fb2ca93fa583fd4804c804c7a30af25b233bc3ca486e0f750/detection

Just a heads up, not sure if this is related to https://github.com/tapahob/BG2RadarOverlay/issues/17

**Comment by tapahob** [comment]
Thank you for reporting that - not sure what to do about it.
I'll have a look at it next week but it would be of help if someone could build the last release and upload it to virus total.

Guys, may I ask you to help with it?
@livelylion @btigi @gatperdut

**Comment by gatperdut** [comment]
I'm away from home for the weekend! But gladly from monday evening/tuesday, if it's still necessary

**Comment by tapahob** [comment]
> I'm away from home for the weekend! But gladly from monday evening/tuesday, if it's still necessary

Please do

**Comment by livelylion** [comment]
> Thank you for reporting that - not sure what to do about it. I'll have a look at it next week but it would be of help if someone could build the last release and upload it to virus total.
> 
> Guys, may I ask you to help with it? @livelylion @btigi @gatperdut

The same result with a binary built from source: [https://www.virustotal.com/gui/file/888e50d46f74eab8b164f337ec9676e361a6cdc088804fe4b893fcabdb1dcc1e](VirusTotal)

**Comment by tapahob** [comment]
Thank you @livelylion !

Im closing the issue then - it is indeed a false positive
