### ISSUE TITLE
Some characters are not displayed corectly

### ISSUE THREAD

**Issue by tarka1939** [tapahob/BG2RadarOverlay#39]
When chosing some characters in SOD, it displays empty frame.
(Viconia selected)
![image](https://github.com/tapahob/BG2RadarOverlay/assets/57870048/8b9ecb22-80d1-4b03-b122-ed0cf9793b7b)

**Comment by tarka1939** [comment]
with some checking, it wont display correctly eny character that equips SoD specific EQ
(after taking off Lon's Amulet, Viconia started to appear again nomaly)

**Comment by tarka1939** [comment]
Managed to resolve that with DLCMerger, but you might to add disclaimer to use it in readme :)

**Comment by tapahob** [comment]
Hii @tarka1939 ! 
Thank you for highlighting this problem. 

Indeed, I don't think anyone tested it without the ModMerge as it is a requirement for other mods.
I'll have the readme updated
