### ISSUE TITLE
Spell protections rename?

### ISSUE THREAD

**Issue by gatperdut** [tapahob/BG2RadarOverlay#4]
The Spell Protections part in the card could use some renaming, I think:

![spell_protections_rename](https://user-images.githubusercontent.com/1401888/171000281-ef65a9c6-3a50-472b-a43a-78e50f6db606.png)

The name can be a bit misleading, spell protections are (Minor) Globe of Invulnerability, Spell Trap... things that protect your other spell buffs like Stoneskin from spellcasters bringing them down. Maybe `Immune to specific spells:` since Insect Plague, Creeping Doom, etc. are actual spell names?

**Comment by tapahob** [comment]
Fixed in the [latest release](https://github.com/tapahob/BG2RadarOverlay/releases/download/1.2.1/BGOverlayUI.7z)
