### ISSUE TITLE
Can't move the NPC list

### ISSUE THREAD

**Issue by comiluv** [tapahob/BG2RadarOverlay#40]
I tried changing the value of `EnemyListXOffset` in `config.cfg` file from 0 to something else.
But when I restart the application the position of the list of NPCs did not change.
I tried values -130, 200, 500 but none seemed to change the location for the list of NPCs, it just stayed in the upper left corner of the screen.

I also tried to build from source to see if I could change the hardcoded offset of 130 from something else, but when I pressed "Build Solution", Visual Studio 2022 produced some dll files instead of a single exe file. Is there any specific build instructions I could follow?

Regards,

**Comment by tapahob** [comment]
Hii!

I havn't finished the enemy list moving function, yesh. I wanted to make it draggable as the other windows but with this list it is a little tricky.

About the compilation thing - there are two projects - backend and frontend basically. You are to select the frontend one (WPF application) - then it would build a bunch of files one of which is the executable.

To make it single file as I ship it you are to click on publish application and choose a single file executable option

**Comment by comiluv** [comment]
Thanks, I found the build target files under `BG2RadarOverlay\WPFFrontend\bin\Release\net7.0-windows`
Closing the issue as stale for now, if anyone else feels different please feel free to open it for further discussion.
