### ISSUE TITLE
See Through Invisibility duplicated

### ISSUE THREAD

**Issue by gatperdut** [tapahob/BG2RadarOverlay#5]
I believe that enemies who see through invisibility are reported to do so in 2 different places. Screenshot from the Crooked Crane Lich:

![see_invisible](https://user-images.githubusercontent.com/1401888/171000898-f15db7fc-a1d5-4ecd-9ded-b352a0cbc33e.png)

Unless there's a difference between the two that I am unaware of? Not really sure what the `1` next to "See Invisible" is, either.

**Comment by tapahob** [comment]
Fixed in the [latest release](https://github.com/tapahob/BG2RadarOverlay/releases/download/1.2.1/BGOverlayUI.7z)
