### ISSUE TITLE
Extend Spell Protections to spell effects?

### ISSUE THREAD

**Issue by gatperdut** [tapahob/BG2RadarOverlay#6]
This is incredible and extremely useful.

![lich_effects](https://user-images.githubusercontent.com/1401888/171002465-f7c3c1a6-db75-4f0f-802a-1a688bd855dd.png)

Could it be extended to all spell effects in general? I am not sure how the filtering is being done, but it only seems to show the beneficial ones - Mirror Image, Stoneskin, Protection from Magical Weapons, that kind of thing. It would be neat to see all that are currently applied, like Slow, ticking acid damage from Melf's Acid Arrow, Khelben's Warding Whip, Barbarian Rage, Hold Person... basically all the relevant effects that are going on for the character, similar to how EEEx does it.

Is this possible? And, do you think the duration left in rounds until they wear off could be displayed next to the icons?

**Comment by tapahob** [comment]
Fixed in the [latest release](https://github.com/tapahob/BG2RadarOverlay/releases/download/1.2.1/BGOverlayUI.7z)
