### ISSUE TITLE
Auto-hide card

### ISSUE THREAD

**Issue by gatperdut** [tapahob/BG2RadarOverlay#7]
I think making the card hide itself when it's no longer needed might make its use seamless.

What do you think of triggering the card not by right click but by hovering + holding Shift, and hiding it automatically when hovering away or releasing Shift?

Closing the card manually by clicking the X can get old very quickly (:

**Comment by tapahob** [comment]
Im not a fan of the idea with holding buttons and hovering but I made it closable with right click anywhere inside the card which is much quicker

**Comment by gatperdut** [comment]
We'll have to agree to disagree (:

I just think it's faster to have the information ready on the press of a key when you need to check something quickly in combat ("Uh, was that guy susceptible to stun?"), then have it disappear immediately once you have the info, than having to manually close a big card that otherwise gets in the way.

But in any case, up to you.

**Comment by gatperdut** [comment]
I think we can close this (:
