### ISSUE TITLE
Crashes in release 1.2.1

### ISSUE THREAD

**Issue by gatperdut** [tapahob/BG2RadarOverlay#9]
I have been experiencing frequent crashes on the latest release 1.2.1.

They seemed to happen mostly when targeting spellcasters. I tried the Lich in the Crooked Crane and Suna Sei in the city random encounter.

Targeting the main character (who was a spellcaster as well) resulted in a crash as well. I am not sure why the main PC is targettable, while Imoen, who previously was, now isn't. IMHO there's no need to target any member of the party.

I couldn't really test the spell effects list with their durations because of this.

This was on BG2EE 2.5, with SCS as the only mod installed.

**Comment by tapahob** [comment]
Spoiler alert - it seems to be working!
![Screenshot 2022-05-31 144215](https://user-images.githubusercontent.com/1484801/171165486-d57097b1-1f8a-48d5-aba7-fbcef26b5583.jpg)

**Comment by gatperdut** [comment]
I'm off to test it

**Comment by gatperdut** [comment]
Yep, definitely more stable now!
